name: Java CI with Maven

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Step 1 - Checkout master branch from Github
      
    - name: Step 2 - Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        java-version: 8.0.302+8
        distribution: 'temurin'
        
    - name: Step 3 - Have Github Actions Build Maven project
      run: mvn -B package --file pom.xml

    - name: Step 4 - List the current directory
      run: ls -la

    - name: Step 5 - List target directory
      run: |
        cd target/
        ls -al
